name: Publish package to the Maven Central Repository

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        java-version: 1.8
        server-id: ossrh
    - name: Set up Apache Maven Central
      uses: actions/setup-java@v3
      with:
        java-version: 1.8
        # Nexus用户名环境变量
        server-username: MAVEN_USERNAME
        # Nexus密码环境变量
        server-password: MAVEN_PASSWORD
        # gpg短密码环境变量
        gpg-passphrase: MAVEN_GPG_PASSPHRASE
        # gpg私钥
        gpg-private-key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
        # 推送jar包至maven中央仓库
    - name: Publish to Apache Maven Central
      # 执行maven deploy命令
      run: mvn clean deploy
      # 环境变量设置
      env:
        # Nexus用户名
        MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        # Nexus密码
        MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        # gpg短密码
        MAVEN_GPG_PASSPHRASE: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
        

